### PR TITLE
Adds circuit wires

### PR DESCRIPTION
**Pull request by cryhot**
I added the following features:
- wires can be selected in the toolbelt and used to connect/disconnect entities
  image
- new settings option: `Limit Wires Length` (on by default). When deactivated, one can move and connect entities even if it makes a wire longer than the max distance. Wires that are too long are indicated as shaded. This feature is helpful for rearranging your circuits without having to cut wires temporarily.
  image

### CODE REVIEW

**Comment by teoxoy** [comment]
This looks great! Thanks for the PR!

There seems to be an issue with the box/hit detection?

https://user-images.githubusercontent.com/28601907/219900207-aae2e327-07f2-4e78-be6d-c29343d390c1.mp4

**Comment by cryhot** [comment]
I see what you mean. I used the entity `selection_box` attribute to detect connection points (see [`getWire_connection_box`](https://github.com/teoxoy/factorio-blueprint-editor/pull/248/commits/39d249c08a678e2e006f1bf8a3d836467f529561#diff-8056c615dec7f9f84e10209a6ccab837fd3f48de9d4bf21c776b0d00733bed9eR891-R912)). It is smaller that a cell for some entities like inserters and power poles (and I'm not even talking about entities with multiple connection points).

On the other hand, [`getEntityAtPosition`](https://github.com/teoxoy/factorio-blueprint-editor/pull/248/commits/39d249c08a678e2e006f1bf8a3d836467f529561#diff-a4be42b10bebcaa87e87a05e768a10fa532e2a64a1498804407e4aa205cf4c2bL59-L68) return entities based on the cell. This leads to a situation where if the cursor is on a cell of an entity but not inside any of the connection points bounding boxes, then it shows the entity as "not connectable".

I'm not sure if we want to make the connection point hitbox bigger, or if we want to make [`getEntityAtPosition`](https://github.com/teoxoy/factorio-blueprint-editor/pull/248/commits/39d249c08a678e2e006f1bf8a3d836467f529561#diff-a4be42b10bebcaa87e87a05e768a10fa532e2a64a1498804407e4aa205cf4c2bL59-L68) consider the `selection_box` attribute.

**Comment by cryhot** [comment]
I fixed the hitbox problem. Also fixed the settings problem.
Also added the following feature:
- wire switches from red to green when pressing R

**Review by teoxoy — APPROVED** [review]
Looks great! Thanks for the PR!

**Pull request merged**
