### PR TITLE
Bug/electric pole paste

### PR DESCRIPTION
**Pull request by smithtad**
Added code to connect newly pasted electric poles

### CODE REVIEW

**Comment by teoxoy** [comment]
@smithtad I think something went wrong and the train commit somehow ended up in this branch/PR as well.

**Comment by smithtad** [comment]
It should be ok if you approve the other PR first. Or do you want me to
redo it?

**Comment by teoxoy** [comment]
@smithtad I requested some changes in the other PR, so I guess the commits here will diverge

**Comment by smithtad** [comment]
I'll redo this one.

**Pull request closed without merging**
