### PR TITLE
Update to Factorio 1.1.107

### PR DESCRIPTION
**Pull request by sighnwaive**
Updates the extractor to v1.1.104 (Current Stable)

### CODE REVIEW

**Comment by sighnwaive** [comment]
Updates the extractor to v1.1.107 (Current Stable)

**Comment by teoxoy** [comment]
Didn't the graphics change as well?

**Comment by sighnwaive** [comment]
I'll read back over the change log and make sure i didn't miss anything.  I just kinda updated the version and grabbed all the "exported" data from the extraction.  I didn't really think to check what changed between the versions.

For what it's worth, I haven't found any functionality issues while using the FBE

**Comment by teoxoy** [comment]
Usually I check the `data.json` just to be aware of any potentially problematic changes.

**Comment by teoxoy** [comment]
I'll update FBE to v2 soon.

**Pull request closed without merging**
