### PR TITLE
Fixed effect of beacon for assembling machine

### PR DESCRIPTION
**Pull request by Disparity**
Fixes for https://github.com/Teoxoy/factorio-blueprint-editor/issues/218

### CODE REVIEW

**Comment by Disparity** [comment]
I can't check rebased commit because of rebased command **yarn start**(yarn start:backend) can't run on win =(

**Comment by Teoxoy** [comment]
Oh, I need to update the contributing document to include rust.
I think to get up and running, you are missing [rust](https://www.rust-lang.org/tools/install) and [systemfd](https://github.com/mitsuhiko/systemfd/blob/master/README.md#installation).

Let me know if it works and I will then update the docs.

**Comment by Teoxoy** [comment]
How is the performance of the implementation for blueprints with quite a lot of beacons (100+)?

**Comment by Disparity** [comment]
@Teoxoy sorry for a late reply, 
I can not run rust (and backend) on windows 10, i get a lot of dependency errors.

>  How is the performance of the implementation for blueprints with quite a lot of beacons (100+)?

The complexity of algorithm is O(n) so the performance is directly proportional to the number of elements in the blueprint. Each beacon is ckecked is for being in a specific area in which it can have an effect on this building (using a few arithmetic operations).

**Comment by Teoxoy** [comment]
Ok, thanks!
Just to let you know, it might take a while until I can merge this PR. I might want to optimize this feature by making it O(1) - since it will be needed for #21 and I'm still working on optimizing the backend for the new release process (everything is blocked by this right now).

**Comment by ZephD** [comment]
> Oh, I need to update the contributing document to include rust.
> I think to get up and running, you are missing [rust](https://www.rust-lang.org/tools/install) and [systemfd](https://github.com/mitsuhiko/systemfd/blob/master/README.md#installation).
> 
> Let me know if it works and I will then update the docs.

and cargo-watch

**Pull request merged**
